version: '3.8'

services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/
      - ./data/mysql/:/var/lib/mysql
    networks:
      - my-network

  app:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    command: ["./wait-for-it.sh", "mysql:3306", "--", "./main", "go", "run", "./init/initTable.go"]
    depends_on:
      - mysql
    networks:
      - my-network

#  nginx:
#    image: nginx:latest
#    restart: unless-stopped
#    ports:
#      - "8080:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    depends_on:
#      - app
#    networks:
#      - my-network

networks:
  my-network:

