info:
  contact: {}
paths:
  /index:
    get:
      responses:
        "200":
          description: '{"code":200,"message":"Go chat"}'
          schema:
            type: string
      summary: 测试连通性
swagger: "2.0"
